# see https://www.mkdocs.org for details
site_name: "AAN: The Alexithymia Awareness Network"
site_url: "https://alexithymiaawarenessnetwork.org"
site_description: "AAN: The Alexithymia Awareness Network"
theme:
  name: material
  custom_dir: theme/
site_dir: "../docs"

# Include CNAME file for GitHub Pages custom domain
extra:
  generator: false

# Copy CNAME file to output directory
plugins:
  - search

# Exclude affiliate config from site build
exclude_docs: |
  affiliate_config.json
  generate_links.py

nav:
  - Home: index.md
  - About Us:
    - Mission: mission.md
    - Network: network.md
    - Advisors: advisors.md
    - Contact: contact.md
  - Emotion Researchers:
    - Plutchik: plutchik.md
    - Ekman: ekman.md
    - Sifneos: sifneos.md
    - Taylor: taylor.md
    - Bagby: bagby.md
    - Parker: parker.md
    - Wilcox: wilcox.md
    - Bermond: bermond.md
    - Vorst: vorst.md
  - Understanding Alexithymia:
    - FAQ: faq.md
    - Lexicon: lexicon.md
  - Resources:
    - Overview: resources.md
    - Apps: apps.md
    - Tools: tools.md
    - Books: books.md
    - Papers: papers.md
    - Podcasts: podcasts.md
  - Research:
    - Studies: studies.md
    - Labs: labs.md
  - Community & Events:
    - Conferences: conferences.md
    - Support: support.md
