# see https://www.mkdocs.org for details
site_name: "AAN: The Alexithymia Awareness Network"
site_url: "https://alexithymiaawarenessnetwork.org"
site_description: "AAN: The Alexithymia Awareness Network"
keywords: "alexithymia, awareness, network, AAN, emotions, feelings, mental health, psychology, psychiatry, neurology, neuroscience, research, support, community, resources, information, education, advocacy, activism, empowerment, acceptance, understanding"
theme: material
site_dir: "../docs"

# Include CNAME file for GitHub Pages custom domain
extra:
  generator: false

# Copy CNAME file to output directory
plugins:
  - search

# Exclude affiliate config from site build
exclude_docs: |
  affiliate_config.json
  generate_links.py

nav:
  - Home: index.md
  - About Us:
    - Mission: mission.md
    - Network: network.md
    - Advisors: advisors.md
    - Contact: contact.md
  - Emotion Researchers:
    - Plutchik: plutchik.md
    - Ekman: ekman.md
  - Understanding Alexithymia:
    - FAQ: faq.md
    - Lexicon: lexicon.md
    - Studies: studies.md
  - Resources:
    - Resources: resources.md
    - Books: books.md
    - Papers: papers.md
    - Podcasts: podcasts.md
    - Tools: tools.md
    - Support: support.md
